services:
  mongodb:
    image: mongo
    container_name: 'enjoyFilms_db'
    volumes:
      - mongo_data:/data/db
    ports: 
      - 27017:27017
    command: mongod

volumes:
  mongo_data: